{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "01_Hello Wall_E",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [
    {
      "Id": "cf8d590febc74babb5a9bd77d87cbfad",
      "Name": "Number",
      "Type": "number",
      "Value": "0",
      "NumberType": "Double",
      "Description": "Creates a number."
    },
    {
      "Id": "4d8b0a67d34549379fc99d4d91b90bc8",
      "Name": "Number",
      "Type": "number",
      "Value": "0",
      "NumberType": "Double",
      "Description": "Creates a number."
    },
    {
      "Id": "0f99c9a3fe9e46fe9a4f409484bc5b66",
      "Name": "Number",
      "Type": "number",
      "Value": "0",
      "NumberType": "Double",
      "Description": "Creates a number."
    },
    {
      "Id": "3221a5bd57184f3abef8c4a53523c873",
      "Name": "Number",
      "Type": "number",
      "Value": "0",
      "NumberType": "Double",
      "Description": "Creates a number."
    }
  ],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "InputValue": 0.0,
      "Id": "cf8d590febc74babb5a9bd77d87cbfad",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "cf10c40cfc65444b9085eb210fdce217",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number."
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "InputValue": 0.0,
      "Id": "4d8b0a67d34549379fc99d4d91b90bc8",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "b1198c710510402b9ad4ecd7df5473a0",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double",
      "Id": "226fc25c91574292b337b89abe52c922",
      "Inputs": [
        {
          "Id": "e19896b76f0e4b2785581956d1b2d5bf",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f8e49784324f47099053917eaa443623",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "392e6dacf9d640ea921c15c28cf1970c",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point in the XY plane given two 2 cartesian coordinates. The Z component is 0.\n\nPoint.ByCoordinates (x: double = 0, y: double = 0): Point"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "InputValue": 0.0,
      "Id": "0f99c9a3fe9e46fe9a4f409484bc5b66",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "8c2d897a44ec48458927eb0ae57aff8c",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double",
      "Id": "c81e7e5de23449e7a3c476dc2f8f96ef",
      "Inputs": [
        {
          "Id": "383158f11ca44138a2f95d0aaa049522",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "9f181664171f45fc9aee274f14aaed28",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "e56f6417f303492bae5fbddf72cbad94",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point in the XY plane given two 2 cartesian coordinates. The Z component is 0.\n\nPoint.ByCoordinates (x: double = 0, y: double = 0): Point"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "InputValue": 0.0,
      "Id": "3221a5bd57184f3abef8c4a53523c873",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "df4293f8eb344f558c20598efc9fc067",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "1f502a38e81944eabe0571e948d97733",
      "Inputs": [
        {
          "Id": "869b57ff671d4ddaad44fc54ac988928",
          "Name": "startPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b73722a2e51b426496a3b7340be96605",
          "Name": "endPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2a947ae57dfc4cc3ac657e4c4add9566",
          "Name": "Line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    }
  ],
  "Connectors": [
    {
      "Start": "cf10c40cfc65444b9085eb210fdce217",
      "End": "f8e49784324f47099053917eaa443623",
      "Id": "2f31a33062fc4c38a1189de8c667fd0c"
    },
    {
      "Start": "b1198c710510402b9ad4ecd7df5473a0",
      "End": "e19896b76f0e4b2785581956d1b2d5bf",
      "Id": "ad97d0a1ddca472aad516ab359995afd"
    },
    {
      "Start": "392e6dacf9d640ea921c15c28cf1970c",
      "End": "869b57ff671d4ddaad44fc54ac988928",
      "Id": "be4523c7636e4e83bd31607014f2a460"
    },
    {
      "Start": "8c2d897a44ec48458927eb0ae57aff8c",
      "End": "383158f11ca44138a2f95d0aaa049522",
      "Id": "9cf15bca430f4a03851bd8df643e33ed"
    },
    {
      "Start": "e56f6417f303492bae5fbddf72cbad94",
      "End": "b73722a2e51b426496a3b7340be96605",
      "Id": "6a1c38a16e5a47fea60f81fa6fdd7e14"
    },
    {
      "Start": "df4293f8eb344f558c20598efc9fc067",
      "End": "9f181664171f45fc9aee274f14aaed28",
      "Id": "197f9b59b797453c93519216708b9609"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.1.5055",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -16.040325164794922,
      "EyeY": 19.623208999633789,
      "EyeZ": 19.695257186889648,
      "LookX": 12.039064407348633,
      "LookY": -14.963991165161133,
      "LookZ": -25.596639633178711,
      "UpX": 0.11373969912528992,
      "UpY": 0.96363043785095215,
      "UpZ": -0.24182562530040741
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Number",
        "Id": "cf8d590febc74babb5a9bd77d87cbfad",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 158.88448004447,
        "Y": -30.2647636941997
      },
      {
        "ShowGeometry": true,
        "Name": "Number",
        "Id": "4d8b0a67d34549379fc99d4d91b90bc8",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 158.88448004447,
        "Y": -108.44444496406
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "226fc25c91574292b337b89abe52c922",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 392.689832757696,
        "Y": -111.374551574694
      },
      {
        "ShowGeometry": true,
        "Name": "Number",
        "Id": "0f99c9a3fe9e46fe9a4f409484bc5b66",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 160.829515699968,
        "Y": 128.502331659454
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "c81e7e5de23449e7a3c476dc2f8f96ef",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 394.634868413194,
        "Y": 125.57222504882
      },
      {
        "ShowGeometry": true,
        "Name": "Number",
        "Id": "3221a5bd57184f3abef8c4a53523c873",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 160.829515699968,
        "Y": 206.682012929315
      },
      {
        "ShowGeometry": true,
        "Name": "Line.ByStartPointEndPoint",
        "Id": "1f502a38e81944eabe0571e948d97733",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 800.253859525202,
        "Y": 3.57193378971991
      }
    ],
    "Annotations": [],
    "X": -66.930042792005622,
    "Y": 117.93727900939226,
    "Zoom": 0.74769281712332347
  }
}